import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'AI Travel Ageent',
  description: 'Generated by Justin Mitchel and CFE',
}

export default function RootLayout({ children }) {
  const mainClassCSS ="flex min-h-screen flex-col items-center justify-between p-24"
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className={mainClassCSS}>
          {children}
        </main>
      </body>
    </html>
  )
}
